# Generated by Django 2.1.1 on 2018-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0003_blog_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='extra',
            new_name='url',
        ),
    ]
